customCommands:
  - key: "o" # The keybinding to trigger the command
    command: "nvim {{.SelectedFile.Name}}" # The command to execute
    context: "files" # The panel where this command is active
    description: "Open file in VS Code"
